### ISSUE TITLE
New api causing problems

### ISSUE THREAD

**Issue by LazyR1co** [Hyphen-ated/DJBot#29]
So the new youtube api is causing problems in the song requests
getting https://youtube.com/devicesupport all the time.

http://youtube-eng.blogspot.com/2014/03/committing-to-youtube-data-api-v3_4.html

**Comment by Hyphen-ated** [comment]
I'm working on it. the new youtube api is a pain in the butt. every djbot user is going to need to create a developer api key through their google account

**Comment by Hyphen-ated** [comment]
fixed in new djbot release.
instructions for getting a youtube key:
Go to https://console.developers.google.com and create a project. Name it whatever you want.
Then click "APIs and Auth" on the left, then click "APIs" under that. Click "Youtube Data API". Click "Enable API".
Then click "Credentials" on the left. Click "Create New Key" under "Public API Access". Click "Server Key". Click "Create".
Copy the API key it shows you and put that in the youtubeAccessToken field in options.yaml.
