### ISSUE TITLE
DJBot Linux

### ISSUE THREAD

**Issue by EvilTaiga** [Hyphen-ated/DJBot#31]
Hey, is it possible to run Dj Bot on a Linux system? I can't start the .jar and don`t know how to write a startscript or to rewrite the startServer.bat.
It would be awesome if you could help me.

I hope it's all right with my english, am as always uncertain :/
Greetings from germany

ps. I have already tried to run the .bat and the .jar with wine and playonlinux, but both can`t work with it. If I start the .jar with Java nothing happens, if I say them to start in a terminal can u see the window for a short moment and that it.

**Comment by Hyphen-ated** [comment]
I haven't tested it on linux but I don't know of any reason why it shouldn't work.
try "java -jar djbot.jar server options.yaml"

**Comment by EvilTaiga** [comment]
omg, my fault... I only entered "java -jar djbot.jar", thanks :D
I have one more question, is it possible to join a second channel? If we play together and we both are streaming, would we love to hear the same music, that is the reason why we not using nightbot for sq.

**Comment by Hyphen-ated** [comment]
It is not controllable from two channels at the same time; it would probably be a large amount of work to change that.
What you can do is have it join one person's channel, and be controlled from that channel, while having multiple people open the UI page that plays the youtube videos. In options.yaml, set djbotPublic to true, and set a username and password, then have both people visit the djbot page in their browser, but only log in with one of them. (you might need to set up port forwarding or open your firewall in order to make the connection to the djbot page from the second machine)

**Comment by EvilTaiga** [comment]
Thank you for the answer, but that isn't exactly what I mean. To hear the same music isn't the problem, the request are. I want the Bot (or somethin else) in a second channel for the request, so the people can in both channels send requests and are not compelled to go to a specific channel. 
Hope you can help me with that :/

**Comment by Hyphen-ated** [comment]
Sorry I have no plans to do that. maybe you could make a bot that listens in one channel and repeats the requests in the other channel.

**Comment by EvilTaiga** [comment]
If I can do that, I could the bot rewrite :D I have no idea how to make a bot, but i already thought at that and here is the problem that everyone can only send 2 request or is there a option to make a exception for a specific nickname?

**Comment by Hyphen-ated** [comment]
You could do maxSongsPerUser:0 to make it unlimited for everyone, or you could have the "listener bot" be running on the streamer's account, so that djbot will see it as "the streamer is trying to request a bunch of songs, they can do whatever they want."
good luck
